# Generated by Django 5.1.4 on 2026-01-13 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True)),
                ('mood', models.CharField(blank=True, max_length=255)),
                ('medium', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('art_styles', models.CharField(blank=True, max_length=255)),
                ('year_created', models.IntegerField(blank=True)),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
