# Generated by Django 5.1.4 on 2026-01-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlift', '0002_artworkdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkdetails',
            name='artwork',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='artlift.artwork'),
        ),
    ]
