# Generated by Django 5.1.4 on 2026-01-14 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlift', '0006_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='artlift.artwork'),
        ),
    ]
