# Generated by Django 5.1.4 on 2026-01-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artlift', '0008_alter_like_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='accept_commisions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
