import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import NavBar from "@/components/nav/page";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import NavBarV2 from "@/components/nav/nav-v2";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       <SidebarProvider defaultOpen={false}>
            <AppSidebar />
            <SidebarInset>
              {/* <NavBar /> */}
              <NavBarV2/>
              <main className="w-full max-w-160 sm:max-w-160 md:max-w-3xl lg:max-w-5xl xl:max-w-246 mx-auto mt-3 p-0 sm:px-5">{children}</main>
            </SidebarInset>
          </SidebarProvider>
    </div>
  );
}
